### ISSUE TITLE
Exercise 24 incorrectly evaluates based on order of items

### ISSUE THREAD

**Issue by ahall-medullan** [jhusain/learnrx#49] opened 2015-02-19 16:39 UTC
Hey I submitted an answer which contained the same objects but in a different order and it was evaluated as incorrect. My solution preserves the order of the objects in the input.

  return movieLists.concatMap(function(movieList) {
    return movieList.videos.map(function(v){
      return Array.zip(
        v.boxarts.reduce(function(acc, curr){ 
          return curr.width * curr.height < acc.width * acc.height ? curr : acc;
        }),
        v.interestingMoments.filter(function(item){
          return item.type == "Middle";
        }),
        function(left, right){ 
          return { id: v.id, title: v.title, time: right.time, url: left.url }; 
        }
      );
    });
  });

**Comment by despairblue** [comment] 2015-04-30 12:56
duplicate of #7

**Closed** 2015-08-26 02:00 UTC
